Q1. Embedding a query

In [1]:
from embedder import Embedder

embed = Embedder()

q1 = "How does approximate nearest neighbor search work?"

v1 = embed.encode(q1)

In [2]:
v1[0]

np.float64(-0.020582036807885073)

In [3]:
from gitsource import GithubRepositoryDataReader

reader = GithubRepositoryDataReader(
    repo_owner="DataTalksClub",
    repo_name="llm-zoomcamp",
    commit_id="8c1834d",
    allowed_extensions={"md"},
    filename_filter=lambda path: "/lessons/" in path,
)

documents = [file.parse() for file in reader.read()]

Q2. Cosine similarity

In [4]:
doc = next(
    doc
    for doc in documents
    if doc["filename"] == "02-vector-search/lessons/07-sqlitesearch-vector.md"
)
doc_content = doc["content"]
doc_embedding = embed.encode(doc_content)

In [5]:
doc_embedding.dot(v1)

np.float64(0.361070280302606)

Q3. Chunking and search by hand

In [6]:
from gitsource import chunk_documents
chunks = chunk_documents(documents, size=2000, step=1000)

In [7]:
chunk_contents = [chunk["content"] for chunk in chunks]
vectors = embed.encode_batch(chunk_contents)

len(vectors)

295

In [8]:
import numpy as np
X = np.array(vectors)

In [9]:
scores = X.dot(v1)

idx = np.argmax(scores)
idx, scores[idx]

(np.int64(94), np.float64(0.648901732433228))

In [10]:
chunks[94]

{'start': 1000,
 'content': 'rch. We score\nthe query against every document and pick the top ones. It always finds\nthe true top matches, but it pays for that by touching everything.\n\nApproximate nearest neighbor (ANN) search takes a shortcut. Instead of\ncomparing against everything, it first narrows down to a region of\nlikely matches. Then it scores only within that region. It may miss the\nabsolute best match, but the results are still good and it\'s much\nfaster.\n\n```text\nNN (exact):    compare query against ALL documents -> top 5\nANN (approx):  narrow down to a region -> compare within region -> top 5\n```\n\n## sqlitesearch\n\nsqlitesearch is the persistent sibling of minsearch, and it solves both\nproblems at once.\n\nWe already used it in module 1 for persistent text search. It also does\nvector search through its `VectorSearchIndex` class. It stores vectors\nin SQLite, a real on-disk database, and uses ANN strategies for\nretrieval. Because the data lives on disk, one process can write the\nvectors and another can read them back.\n\nIf you didn\'t install it in the previous module, add it to your project:\n\n```bash\nuv add sqlitesearch\n```\n\n## Creating the index\n\nInitialize it:\n\n```python\nfrom sqlitesearch import VectorSearchIndex\n\nvs_index = VectorSearchIndex(\n    keyword_fields=["course"],\n    mode="ivf",\n    db_path="faq_vectors2.db"\n)\n```\n\nsqlitesearch supports three ANN modes:\n\n- `lsh` (default): up to 100K vectors, random hyperplane projections\n- `ivf`: 10K-500K vectors, K-means clustering\n- `hnsw`: 10K-1M+ vectors, proximity graph (highest recall)\n\nFor our small dataset, `lsh` is fine. All modes use two-phase search:\napproximate candidate retrieval, then exact cosine similarity\nreranking.\n\n## Indexing the data\n\nFit the index with our vectors and documents:\n\n```python\nvs_index.fit(vectors, documents)\n```\n\nThe index is saved to `faq_vectors2.db`. Unlike minsearch, this file\npersists on disk. You can search immediately after indexing, or reopen\nthe index later without re-indexing.\n\n## Searching\n\nSearch ',
 'filename': '02-vector-search/lessons/07-sqlitesearch-vector.md'}

Q4. Vector search with minsearch

In [11]:
from minsearch import VectorSearch

vindex = VectorSearch(keyword_fields=['content'])
vindex.fit(X, chunks)

In [12]:
q1 = "What metric do we use to evaluate a search engine?"

v1 = embed.encode(q1)

In [13]:
vindex.search(v1, num_results=5)

[{'start': 0,
  'content': "# Search Evaluation Metrics\n\nVideo: [Watch this lesson](https://www.youtube.com/watch?v=TuirMy3Pdbk&list=PL3MmuxUbc_hLZFNgSad56pDBKK8KO0XIv)\n\nIn the previous lesson, we computed relevance lists for search results.\nWe can turn those lists into metrics.\n\n## Hit Rate\n\nHit Rate (also called Recall@k) measures the fraction of queries where\nthe correct document appears anywhere in the results:\n\n```python\nexample = [\n    [1, 0, 0, 0, 0],\n    [0, 1, 0, 0, 0],\n    [1, 0, 0, 0, 0],\n    [0, 0, 0, 0, 0],\n    [0, 1, 0, 0, 0],\n    [1, 0, 0, 0, 0],\n    [1, 0, 0, 0, 0],\n    [1, 0, 0, 0, 0],\n    [1, 0, 0, 0, 0],\n    [0, 0, 1, 0, 0],\n    [1, 0, 0, 0, 0],\n    [1, 0, 0, 0, 0],\n    [1, 0, 0, 0, 0],\n    [1, 0, 0, 0, 0],\n    [1, 0, 0, 0, 0],\n]\n```\n\nEach line is one query. If a line contains `1`, search found the\ncorrect document somewhere in the top 5 results. If the line contains\nonly zeros, search did not find the correct document.\n\nIn our setup, each query has one correct document, so Hit Rate and\nRecall@k mean the same thing.\n\nLet's calculate it:\n\n```python\ncnt = 0\n\nfor line in example:\n    if 1 in line:\n        cnt = cnt + 1\n\ncnt\n```\n\nThere are 14 hits. The example has 15 queries.\n\nThe Hit Rate is:\n\n```python\ncnt / len(example)\n# 0.933\n```\n\nThis means that search found the correct document for 93.3% of the\nqueries in this example.\n\nPut the same logic into a function:\n\n```python\ndef hit_rate(relevance):\n    cnt = 0\n\n    for line in relevance:\n        if 1 in line:\n            cnt = cnt + 1\n\n    return cnt / len(relevance)\n```\n\nCheck it on the same example:\n\n```python\nhit_rate(example)\n# 0.933\n```\n\n## Mean Reciprocal Rank (MRR)\n\nHit Rate tells us if we found the right document, but not where it was.\n\nMRR also considers the position.\n\nFor each query, the score is based on the rank of the first correct\ndocument:\n\n- position 1: score is 1.0\n- position 2: score is 0.5\n- position 3: score is 0.333\n- not found: score is 0\n\nIn the example, most hits are at the first position. Some hits are\nlo",
  'filename': '04-evaluation/lessons/05-search-metrics.md'},
 {'start': 0,
  'content': "# Evaluation\n\nVideo: [Watch this lesson](https://www.youtube.com/watch?v=eC_IcxfxoiQ&list=PL3MmuxUbc_hLZFNgSad56pDBKK8KO0XIv)\n\nIn the previous modules, we built search engines and RAG pipelines.\nWe tried different approaches: keyword search with minsearch, vector\nsearch, agents with function calling. But we never answered the obvious\nquestion of which one is actually better.\n\nWe could try a few queries by hand and see what looks good. That's fine\nfor a quick sanity check, but it doesn't scale, and it doesn't give us a\nnumber to compare. We need a systematic way to tell whether one approach\nbeats another.\n\nThat's what evaluation is for. And it's worth saying up front: of\neverything in this course, evaluation is the part that matters most. It's\nalso the most tedious. But it's the only way to be sure your system\nworks. And it's how you keep it working as you change prompts and swap\nmodels.\n\n## The evaluation setup\n\nFor search evaluation, we need a dataset of questions where we know\nwhich document is the correct answer. We'll use an LLM to generate\nthese questions from our FAQ data.\n\nThe approach works like this:\n\n- A = the original answer in the FAQ\n- Q* = a question generated from that answer by an LLM\n- We send Q* through our search and check if the original document\n  appears in the results\n\nFor RAG evaluation, we go one step further:\n\n- A = the original answer in the FAQ\n- Q* = a question generated from that answer by an LLM\n- A' = the answer produced by our RAG system when given Q*\n- We compare A' with A to see if the system produced the right answer\n\nThis is the A → Q* → A' pattern. We know the answer for each generated\nquestion because we created the question from that answer.\n\nWith evaluation, we can:\n\n- Compare different search methods (minsearch vs vector search vs hybrid)\n- Tune parameters (boost values, number of results, prompt templates)\n- Compare different LLMs (gpt-5.4-mini vs others)\n- Track improvements over time\n\nThere are two types of evaluation:\n\n-",
  'filename': '04-evaluation/lessons/01-intro.md'},
 {'start': 0,
  'content': '# Search\n\nVideo: [Watch this lesson](https://www.youtube.com/watch?v=GYgpNKiuCJU&list=PL3MmuxUbc_hLZFNgSad56pDBKK8KO0XIv)\n\n## Search basics\n\nAt its core, every search engine does the same thing. It takes a query,\nscores every document for similarity, and returns the top results.\n\nFormally, there is a similarity function:\n\n```python\nscore = sim(query, document)\n```\n\nFor each document in the database, you compute this score. Then you\nrank all documents by score and return the top N. What makes a search\nengine different from another search engine is what `sim` actually\ncomputes.\n\n- text/lexical search (covered in this section): `sim` counts how\n  many words the query and the document share. It looks at the surface\n  form, the actual words, and matches them exactly.\n\n- vector/semantic search (covered in [module 2](../../02-vector-search/)):\n  `sim` compares the meaning of the query and the document. Same\n  function, different similarity measure.\n\nConsider these two questions:\n\n- "Can I still join the course after the start date?"\n- "Is it possible to enroll late?"\n\nThey mean the same thing, but share almost no keywords. "Join" is not\n"enroll", "course" is absent, "start date" is not "late". A text search\nengine would struggle to match them, because it only sees words.\n\nWe\'ll see how vector search solves this later. For now, let\'s build text\nsearch with minsearch.\n\n## Indexing with minsearch\n\nWe already have the `documents` list from the previous section. Now\nlet\'s index it.\n\nSearching matters because we have around 1100 documents. Sending all\nof them to the LLM would be expensive and slow. The model would get\nconfused with too much data. Search finds the most relevant documents\nto send instead.\n\nThere are many search libraries you can use - Apache Lucene,\nElasticsearch, Solr, and others. But these are somewhat heavy. For\nexample, to run Elasticsearch, you need to start a Docker container.\n\n[minsearch](https://github.com/alexeygrigorev/minsearch) is a simple\nin-memory se',
  'filename': '01-agentic-rag/lessons/05-search.md'},
 {'start': 2000,
  'content': " Offline evaluation: run the system on a test dataset and compute metrics\n- Online evaluation: collect feedback from real users in production\n\nOffline evaluation is what we do before putting changes in front of\nusers. It lets us compare search settings, prompts, or models on the\nsame dataset. Online evaluation happens after deployment. It uses real\ntraffic, feedback, logs, and dashboards to monitor quality.\n\nIn this module, we focus on offline evaluation. We'll generate a test\ndataset, run our search and RAG systems on it, and measure how well they\nperform.\n\nSynthetic data is a good starting point when you don't have real user\ndata. But generated questions can be too similar to the original FAQ\ntext, which inflates the metrics. As soon as you can, start collecting\nreal user queries and use them to validate your evaluation framework.\n\nWe'll cover three levels of evaluation:\n\n1. Search evaluation: does the search return the right documents?\n2. RAG evaluation: does the LLM generate good answers?\n3. Agent evaluation: does the agent use tools efficiently?\n\nMost of our time goes to search, and that's on purpose. Everything else\ndepends on it: if retrieval brings back the wrong documents, no prompt or\nmodel can rescue the answer. So we test search on its own first, then\nevaluate the full pipeline on top of it.\n\nFor search, we'll use two metrics: Hit Rate and MRR (Mean Reciprocal\nRank). For RAG quality, we'll use LLM-as-a-judge. For agents, we'll\nlook at the final answer and the tool-call trajectory.\n\nLet's start with generating the test data we need.\n\n[← Back to module](../) | [Generating Ground Truth Data →](02-ground-truth.md)",
  'filename': '04-evaluation/lessons/01-intro.md'},
 {'start': 0,
  'content': "# Next Steps\n\nVideo: [Watch this lesson](https://www.youtube.com/watch?v=TlKPBjItUw8&list=PL3MmuxUbc_hLZFNgSad56pDBKK8KO0XIv)\n\nIn this module, we covered evaluation at three levels:\n\n1. Search evaluation: Hit Rate and MRR to measure retrieval quality\n2. RAG evaluation: LLM-as-a-judge for answer quality\n3. Agent evaluation: final answers plus tool-call trajectories\n\nEvaluation is not a one-time activity. As you tune search parameters,\nswitch models, or modify prompts, re-run evaluation. Make sure the\nsystem is getting better, not worse.\n\nEvaluation is the most important part of building AI systems. It is also\nthe most time-consuming. Only after evaluation can you be confident\nthat your system works. Validate every change against your evaluation\nframework before going to production. This applies to prompt updates,\nmodel swaps, and agent modifications.\n\n## From synthetic data to real data\n\nThe evaluation workflow in practice:\n\n1. Start with synthetic data. Use an LLM to generate questions from\n   your FAQ or documentation. This gives you a baseline without needing\n   real users.\n2. Tune the data generation. If the metrics look suspiciously good,\n   the synthetic questions may be too close to the source text. Adjust\n   the generation prompt to produce more realistic questions.\n3. Deploy and collect real data. Once the system is in production, start\n   collecting actual user queries and feedback.\n4. Label real data. Have humans label whether the retrieved documents\n   and generated answers are correct. This produces the most reliable\n   ground truth.\n5. Tune synthetic generation to match real data. Use the patterns from\n   real queries to improve your synthetic data generator. The closer\n   your synthetic data is to real data, the more useful the metrics\n   become.\n\nNothing beats manual evaluation. Try the system yourself, think about\nedge cases, and collect examples of where it fails. This is especially\nimportant in the early stages when you don't have automated evaluat",
  'filename': '04-evaluation/lessons/15-next-steps.md'}]

Q5. Text search vs vector search

In [14]:
# vector search with new query
from minsearch import VectorSearch

vindex = VectorSearch(keyword_fields=['content'])
vindex.fit(X, chunks)
q1 = "How do I store vectors in PostgreSQL?"
v1 = embed.encode(q1)
vindex.search(v1, num_results=5)

[{'start': 0,
  'content': '# Vector Search with PGVector\n\nVideo: [Watch this lesson](https://www.youtube.com/watch?v=0P54MFyz-mc&list=PL3MmuxUbc_hLZFNgSad56pDBKK8KO0XIv)\n\nMany real databases can do vector search. Elasticsearch has it, and\nthere are dedicated stores like Qdrant and Chroma. We\'ll go with\nPostgres. Most of us already run it at work, and the data engineering\ncourse uses it too. The concept is the same as with sqlitesearch, only\nthe database under the hood changes.\n\n[pgvector](https://github.com/pgvector/pgvector) is the PostgreSQL\nextension that makes this work. Install it and Postgres can do vector\nsimilarity search. On top of that you get the usual production features,\nlike concurrent access, transactions, and large datasets.\n\nWe\'ll run Postgres with pgvector in Docker.\n\n## Starting Postgres with pgvector\n\nPull the image and start a container:\n\n```bash\ndocker run -it \\\n    --name pgvector \\\n    -e POSTGRES_USER=user \\\n    -e POSTGRES_PASSWORD=pswd \\\n    -e POSTGRES_DB=faq \\\n    -v pgvector_data:/var/lib/postgresql/data \\\n    -p 5432:5432 \\\n    pgvector/pgvector:pg17\n```\n\nThis image has the pgvector extension pre-installed. The `-v` flag\ncreates a named volume so data persists across container restarts.\n\n## Installing the Python client\n\nInstall the driver:\n\n```bash\nuv add psycopg[binary]\n```\n\nWe\'ll use `psycopg` (v3) to connect and run queries. Note: this is\ndifferent from `psycopg2` - psycopg v3 supports `conn.execute()`\ndirectly without creating a cursor.\n\n## Preparing the data\n\nWe need the FAQ documents and their embeddings.\n\nHere\'s what we did in previous units as one script:\n\n```python\nfrom tqdm.auto import tqdm\n\nfrom ingest import load_faq_data\nfrom sentence_transformers import SentenceTransformer\n\nmodel = SentenceTransformer("all-MiniLM-L6-v2")\n\ndocuments = load_faq_data()\ntexts = [doc["question"] + " " + doc["answer"] for doc in documents]\n\nbatch_size = 50\nvectors = []\n\nfor i in tqdm(range(0, len(texts), batch_size)):\n    batch = texts[i:i + batch_size]\n    batch_vectors',
  'filename': '02-vector-search/lessons/08-pgvector.md'},
 {'start': 3000,
  'content': 'PGVector:\n\n```python\ndef vec_to_str(vector):\n    return "[" + ",".join(str(x) for x in vector) + "]"\n\nfor doc, vec in tqdm(zip(documents, vectors), total=len(documents)):\n    conn.execute(\n        """\n        INSERT INTO documents (course, section, question, answer, embedding)\n        VALUES (%s, %s, %s, %s, %s::vector)\n        """,\n        (doc["course"], doc["section"], doc["question"], doc["answer"],\n         vec_to_str(vec))\n    )\n\nconn.commit()\n```\n\nWe loop over the documents and insert each one with its embedding. We\nhand Postgres the vector as text, so the `::vector` cast tells it to\nparse that string back into a vector. We call `conn.commit()` to persist\nthe changes.\n\n## Searching with cosine similarity\n\nSearch with a query:\n\n```python\nquery = "I just discovered the course. Can I still join it?"\nquery_vector = model.encode(query)\nquery_str = vec_to_str(query_vector)\n```\n\nSearch for the most similar documents:\n\n```python\nresults = conn.execute(\n    """\n    SELECT course, question, answer,\n           1 - (embedding <=> %s::vector) AS similarity\n    FROM documents\n    ORDER BY embedding <=> %s::vector\n    LIMIT 5\n    """,\n    (query_str, query_str)\n).fetchall()\n\nfor row in results:\n    print(f"[{row[0]}] {row[1]} (similarity: {row[3]:.4f})")\n```\n\nThe `<=>` operator computes cosine distance (1 - cosine similarity).\nWe order by ascending distance, so the closest vectors come first.\n\n## Filtering by course\n\nBecause this is plain SQL, filtering by course is one extra `WHERE`\nclause:\n\n```python\nresults = conn.execute(\n    """\n    SELECT course, question, answer,\n           1 - (embedding <=> %s::vector) AS similarity\n    FROM documents\n    WHERE course = %s\n    ORDER BY embedding <=> %s::vector\n    LIMIT 5\n    """,\n    (query_str, "llm-zoomcamp", query_str)\n).fetchall()\n```\n\n## Creating an index for faster search\n\nSo far this runs brute-force search, comparing our query against every\nrow. For our small dataset that\'s fine.\n\nFor a larger one, create an HNSW index to ',
  'filename': '02-vector-search/lessons/08-pgvector.md'},
 {'start': 2000,
  'content': 'ale demos, but it is not a replacement for a proper vector database. For any serious workload, e.g. larger document sets, low-latency retrieval, or production use, you should use a dedicated vector store. See [Module 2: Vector Search](../../02-vector-search/lessons/04-vector-search.md) for a deeper look at vector search in practice.\n\nQuery phase (runs every time a question is asked):\n\n4. Retrieve context: find the embeddings most similar to the user\'s question\n5. Augment the prompt: add the retrieved content to the LLM prompt\n6. Generate response: the LLM answers using real, grounded context\n\n## Example: Kestra Release Features\n\n### Step 1: Without RAG\n\nFlow: [`1_chat_without_rag.yaml`](../flows/1_chat_without_rag.yaml)\n\nThis flow asks Gemini: "Which features were released in Kestra 1.1?"\n\nWithout RAG, the model might hallucinate features that don\'t exist, provide outdated information, or give vague generic answers.\n\nImport and run this flow, then check the output — the response won\'t be accurate.\n\n### Step 2: With RAG\n\nFlow: [`2_chat_with_rag.yaml`](../flows/2_chat_with_rag.yaml)\n\nThis flow:\n\n1. Ingests the Kestra 1.1 release blog post from GitHub\n2. Creates embeddings using Gemini\'s embedding model\n3. Stores embeddings in Kestra\'s KV Store\n4. Asks the LLM the same question with RAG enabled\n5. Returns an accurate response with real features from that release\n\nImport and run `2_chat_with_rag.yaml` and compare the output quality against the previous flow.\n\n## Extending RAG with web search\n\nThe examples above use static RAG — documents are ingested once and stored in the KV Store. Kestra also supports web search as a retriever, which fetches live results at query time and passes them as context to the LLM.\n\nFlow: [`3_rag_with_websearch.yaml`](../flows/3_rag_with_websearch.yaml)\n\n> Note: This flow uses OpenAI as its AI provider. To run it, you\'ll need an OpenAI API key:\n>\n> 1. Visit [platform.openai.com](https://platform.openai.com/home) and sign in or create an accoun',
  'filename': '03-orchestration/lessons/05-rag.md'},
 {'start': 1000,
  'content': 'ar/lib/postgresql/data \\\n    -p 5432:5432 \\\n    pgvector/pgvector:pg17\n```\n\nThis image has the pgvector extension pre-installed. The `-v` flag\ncreates a named volume so data persists across container restarts.\n\n## Installing the Python client\n\nInstall the driver:\n\n```bash\nuv add psycopg[binary]\n```\n\nWe\'ll use `psycopg` (v3) to connect and run queries. Note: this is\ndifferent from `psycopg2` - psycopg v3 supports `conn.execute()`\ndirectly without creating a cursor.\n\n## Preparing the data\n\nWe need the FAQ documents and their embeddings.\n\nHere\'s what we did in previous units as one script:\n\n```python\nfrom tqdm.auto import tqdm\n\nfrom ingest import load_faq_data\nfrom sentence_transformers import SentenceTransformer\n\nmodel = SentenceTransformer("all-MiniLM-L6-v2")\n\ndocuments = load_faq_data()\ntexts = [doc["question"] + " " + doc["answer"] for doc in documents]\n\nbatch_size = 50\nvectors = []\n\nfor i in tqdm(range(0, len(texts), batch_size)):\n    batch = texts[i:i + batch_size]\n    batch_vectors = model.encode(batch)\n    vectors.extend(batch_vectors)\n```\n\n\nNow we connect to Postgres:\n\n```python\nimport psycopg\n\nconn = psycopg.connect(\n    "postgresql://user:pswd@localhost:5432/faq"\n)\nconn.execute("CREATE EXTENSION IF NOT EXISTS vector")\n```\n\nThe second line activates pgvector. The Docker image we started isn\'t\nplain Postgres, it ships the extension inside, and this turns it on. It\nadds the `vector` column type and the similarity search operators.\n\n## Creating a table\n\nCreate a table for storing documents with their embeddings:\n\n```python\nconn.execute("""\n    DROP TABLE IF EXISTS documents\n""")\n\nconn.execute("""\n    CREATE TABLE documents (\n        id SERIAL PRIMARY KEY,\n        course TEXT,\n        section TEXT,\n        question TEXT,\n        answer TEXT,\n        embedding vector(384)\n    )\n""")\n```\n\nThe `vector(384)` column stores our 384-dimensional embeddings from\n`all-MiniLM-L6-v2`.\n\n## Inserting documents with embeddings\n\nLet\'s insert the documents and their vectors into ',
  'filename': '02-vector-search/lessons/08-pgvector.md'},
 {'start': 2000,
  'content': ' = model.encode(batch)\n    vectors.extend(batch_vectors)\n```\n\n\nNow we connect to Postgres:\n\n```python\nimport psycopg\n\nconn = psycopg.connect(\n    "postgresql://user:pswd@localhost:5432/faq"\n)\nconn.execute("CREATE EXTENSION IF NOT EXISTS vector")\n```\n\nThe second line activates pgvector. The Docker image we started isn\'t\nplain Postgres, it ships the extension inside, and this turns it on. It\nadds the `vector` column type and the similarity search operators.\n\n## Creating a table\n\nCreate a table for storing documents with their embeddings:\n\n```python\nconn.execute("""\n    DROP TABLE IF EXISTS documents\n""")\n\nconn.execute("""\n    CREATE TABLE documents (\n        id SERIAL PRIMARY KEY,\n        course TEXT,\n        section TEXT,\n        question TEXT,\n        answer TEXT,\n        embedding vector(384)\n    )\n""")\n```\n\nThe `vector(384)` column stores our 384-dimensional embeddings from\n`all-MiniLM-L6-v2`.\n\n## Inserting documents with embeddings\n\nLet\'s insert the documents and their vectors into PGVector:\n\n```python\ndef vec_to_str(vector):\n    return "[" + ",".join(str(x) for x in vector) + "]"\n\nfor doc, vec in tqdm(zip(documents, vectors), total=len(documents)):\n    conn.execute(\n        """\n        INSERT INTO documents (course, section, question, answer, embedding)\n        VALUES (%s, %s, %s, %s, %s::vector)\n        """,\n        (doc["course"], doc["section"], doc["question"], doc["answer"],\n         vec_to_str(vec))\n    )\n\nconn.commit()\n```\n\nWe loop over the documents and insert each one with its embedding. We\nhand Postgres the vector as text, so the `::vector` cast tells it to\nparse that string back into a vector. We call `conn.commit()` to persist\nthe changes.\n\n## Searching with cosine similarity\n\nSearch with a query:\n\n```python\nquery = "I just discovered the course. Can I still join it?"\nquery_vector = model.encode(query)\nquery_str = vec_to_str(query_vector)\n```\n\nSearch for the most similar documents:\n\n```python\nresults = conn.execute(\n    """\n    SELECT course, questio',
  'filename': '02-vector-search/lessons/08-pgvector.md'}]

In [15]:
# indexsearch with new query

from minsearch import Index

index = Index(text_fields=['content'], keyword_fields=['content'])
index.fit(chunks)
index.search("How do I store vectors in PostgreSQL?", num_results=5)

[{'start': 4000,
  'content': 'get 0.01.\n\nThe first score for `q1` vs `d` (0.32) is higher, so that query is more\nsimilar to the document about registration. The second score for `q2`\nvs `d` sits near 0, because installing Docker has nothing to do with\nregistration. A score near 0 means the two vectors are about as\ndifferent as they can be.\n\nThat\'s the whole idea behind vector search: similar texts get similar\nvectors, and a dot product tells us how similar.\n\n## Cosine similarity\n\nThe `all-MiniLM-L6-v2` model outputs normalized vectors - vectors with\nunit length. When both vectors are normalized, the dot product equals\ncosine similarity. That\'s why the model documentation says it "uses\ncosine similarity."\n\nCosine similarity measures the angle between two vectors, ignoring\ntheir length:\n\n- 1.0 = same direction (similar)\n- 0.0 = perpendicular (unrelated)\n- -1.0 = opposite direction (opposite meaning)\n\nFormally, if `theta` is the angle between two vectors, cosine similarity\nis `cos(theta)`:\n\n- `cos(0) = 1` - vectors point in the same direction\n- `cos(90) = 0` - vectors are perpendicular\n- `cos(180) = -1` - vectors point in opposite directions\n\nBecause our vectors are normalized, the dot product gives us cosine\nsimilarity directly. This is why we can use `v1.dot(dv)` to compare\ntexts.\n\nIn practice, we rarely get cosine similarity below 0. The embedding\nmodel maps text to a region of the vector space where most vectors\nhave positive components. There\'s no concept of "opposite meaning"\nthat maps to a vector pointing the other way.\n\n[← What is Vector Search](01-intro.md) | [Embedding Our Dataset →](03-embeddings-dataset.md)',
  'filename': '02-vector-search/lessons/02-embeddings.md'},
 {'start': 1000,
  'content': 'arch](../../02-vector-search/lessons/04-vector-search.md).\n\n## How RAG Works in Kestra\n\nRAG has two phases. In the demo flows below they run back-to-back, but in production you\'d typically schedule them separately — ingest on a cadence, query on demand.\n\n```mermaid\ngraph LR\n    subgraph Ingest ["Ingest (run once / on schedule)"]\n        A[Fetch Docs] --> B[Create Embeddings]\n        B --> C[Store in KV Store]\n    end\n    subgraph Query ["Query (run on demand)"]\n        D[User Question] --> E[Find Similar Content]\n        E --> F[Add Context to Prompt]\n        F --> G[LLM Answer]\n    end\n    C --> E\n```\n\nIngest phase (run once, or on a schedule when your data changes):\n\n1. Fetch documents: load documentation, release notes, or other data sources\n2. Create embeddings: convert text into vectors using an embedding model\n3. Store embeddings: save vectors in Kestra\'s KV Store\n\n> Note: The flows store embeddings in Kestra\'s KV Store for simplicity. This is convenient for learning and small-scale demos, but it is not a replacement for a proper vector database. For any serious workload, e.g. larger document sets, low-latency retrieval, or production use, you should use a dedicated vector store. See [Module 2: Vector Search](../../02-vector-search/lessons/04-vector-search.md) for a deeper look at vector search in practice.\n\nQuery phase (runs every time a question is asked):\n\n4. Retrieve context: find the embeddings most similar to the user\'s question\n5. Augment the prompt: add the retrieved content to the LLM prompt\n6. Generate response: the LLM answers using real, grounded context\n\n## Example: Kestra Release Features\n\n### Step 1: Without RAG\n\nFlow: [`1_chat_without_rag.yaml`](../flows/1_chat_without_rag.yaml)\n\nThis flow asks Gemini: "Which features were released in Kestra 1.1?"\n\nWithout RAG, the model might hallucinate features that don\'t exist, provide outdated information, or give vague generic answers.\n\nImport and run this flow, then check the output — the response won\'t ',
  'filename': '03-orchestration/lessons/05-rag.md'},
 {'start': 0,
  'content': '# Vector Search\n\nVideo: [Watch this lesson](https://www.youtube.com/watch?v=qyZgxTmC2cY&list=PL3MmuxUbc_hLZFNgSad56pDBKK8KO0XIv)\n\nIn module 1 we used keyword search with minsearch and sqlitesearch.\nIt matches exact words. If you search for "Docker", the document has\nto contain "Docker" to come back.\n\nBut look at these two questions:\n\n- "Can I still join the course after the start date?"\n- "Is it possible to enroll late?"\n\nThey mean the same thing, yet they share almost no words. A keyword\nengine struggles to match them. We need something that works on\nmeaning, not on the exact words.\n\nThat something is vector search. Instead of matching words, it matches\nideas.\n\n## The vector search process\n\nWe run vector search in two stages.\n\n1. Offline (indexing): we convert all documents into vectors (arrays\n   of numbers) and store them in an index.\n2. Online (querying): we convert the user\'s query into a vector with\n   the same model, then find the closest document vectors by similarity.\n\nAn embedding model produces these vectors. It\'s a neural network\ntrained to capture meaning, so texts that mean similar things land on\nsimilar vectors. We measure how close two vectors are with a distance\nmetric. The most common one is cosine similarity.\n\nCosine similarity measures the angle between two vectors:\n\n- Vectors pointing in the same direction: similarity close to 1\n  (similar)\n- Vectors at right angles: similarity close to 0 (unrelated)\n- Vectors pointing in opposite directions: similarity close to -1\n  (opposite meaning)\n\nThe larger the cosine similarity, the more similar the two texts are\nin meaning.\n\n## Keyword search vs vector search\n\nHere\'s how the two approaches differ:\n\n- Keyword search matches exact words. Vector search matches meaning.\n- Keyword search suits specific terms, IDs, and names. Vector search\n  suits paraphrased questions and natural language.\n- Keyword search example: "pandas dataframe". Vector search example:\n  "How do I work with tabular data?"\n- Keyword sear',
  'filename': '02-vector-search/lessons/01-intro.md'},
 {'start': 0,
  'content': '# Retrieval Augmented Generation\n\nVideo: [RAG Workflows](https://youtu.be/FhGZV173xrk)\n\nAI Copilot solves the context problem for flow generation. But what about workflows that need to answer questions from your own data? That\'s where RAG comes in.\n\n> Note: Flows 1 and 2 use `{{ secret(\'GEMINI_API_KEY\') }}`. Flow 3 uses `{{ secret(\'OPENAI_API_KEY\') }}` and `{{ secret(\'TAVILY_API_KEY\') }}`. Make sure you\'ve completed the [setup instructions](03-setup.md) to configure the relevant secrets before running them.\n\n## What is RAG?\n\nRAG (Retrieval Augmented Generation) is a technique that retrieves relevant information from your data sources, augments the AI prompt with that context, and generates a response grounded in real data. This solves the hallucination problem by ensuring the AI has access to current, accurate information at query time.\n\nFor a deeper dive into RAG concepts, see [Module 1: Intro to RAG](../../01-agentic-rag/lessons/03-rag.md). For vector search, see [Module 2: Vector Search](../../02-vector-search/lessons/04-vector-search.md).\n\n## How RAG Works in Kestra\n\nRAG has two phases. In the demo flows below they run back-to-back, but in production you\'d typically schedule them separately — ingest on a cadence, query on demand.\n\n```mermaid\ngraph LR\n    subgraph Ingest ["Ingest (run once / on schedule)"]\n        A[Fetch Docs] --> B[Create Embeddings]\n        B --> C[Store in KV Store]\n    end\n    subgraph Query ["Query (run on demand)"]\n        D[User Question] --> E[Find Similar Content]\n        E --> F[Add Context to Prompt]\n        F --> G[LLM Answer]\n    end\n    C --> E\n```\n\nIngest phase (run once, or on a schedule when your data changes):\n\n1. Fetch documents: load documentation, release notes, or other data sources\n2. Create embeddings: convert text into vectors using an embedding model\n3. Store embeddings: save vectors in Kestra\'s KV Store\n\n> Note: The flows store embeddings in Kestra\'s KV Store for simplicity. This is convenient for learning and small-sc',
  'filename': '03-orchestration/lessons/05-rag.md'},
 {'start': 1000,
  'content': 'dding model produces these vectors. It\'s a neural network\ntrained to capture meaning, so texts that mean similar things land on\nsimilar vectors. We measure how close two vectors are with a distance\nmetric. The most common one is cosine similarity.\n\nCosine similarity measures the angle between two vectors:\n\n- Vectors pointing in the same direction: similarity close to 1\n  (similar)\n- Vectors at right angles: similarity close to 0 (unrelated)\n- Vectors pointing in opposite directions: similarity close to -1\n  (opposite meaning)\n\nThe larger the cosine similarity, the more similar the two texts are\nin meaning.\n\n## Keyword search vs vector search\n\nHere\'s how the two approaches differ:\n\n- Keyword search matches exact words. Vector search matches meaning.\n- Keyword search suits specific terms, IDs, and names. Vector search\n  suits paraphrased questions and natural language.\n- Keyword search example: "pandas dataframe". Vector search example:\n  "How do I work with tabular data?"\n- Keyword search uses an inverted index (BM25, TF-IDF). Vector search\n  uses a vector index based on cosine similarity.\n- Keyword search misses synonyms and paraphrases. Vector search misses\n  exact term matches.\n\nVector search is usually better, but it adds a lot of operational\ncomplexity, and you\'ll feel that throughout this module. So my advice\nis to never start with vector search. Start with text search, and reach\nfor vectors once you can show they\'re worth the extra cost.\n\nIn practice the two work best together. Hybrid search combines them,\nand we cover it in the\n[Best Practices module](../../06-best-practices/lessons/02-hybrid-search.md).\n\n## Building vector search\n\nWe\'ll take the same FAQ dataset from module 1 and build vector search\nwith three tools:\n\n1. minsearch - in-memory vector search (simplest, good for\n   experiments)\n2. sqlitesearch - persistent vector search backed by SQLite\n   (production-friendly, same API as minsearch)\n3. PGVector - vector search in PostgreSQL (scalable, runs in\n',
  'filename': '02-vector-search/lessons/01-intro.md'}]

Q6. Hybrid search

In [16]:
def rrf(result_lists, k=60, num_results=5):
    scores = {}
    docs = {}

    for results in result_lists:
        for rank, doc in enumerate(results):
            key = (doc["filename"], doc["start"])
            scores[key] = scores.get(key, 0) + 1 / (k + rank)
            docs[key] = doc

    ranked = sorted(scores, key=scores.get, reverse=True)
    return [docs[key] for key in ranked[:num_results]]

In [17]:
# vector search with new query
from minsearch import VectorSearch

vindex = VectorSearch(keyword_fields=['content'])
vindex.fit(X, chunks)
q1 = "How do I give the model access to tools?"
v1 = embed.encode(q1)

vector_results = vindex.search(v1, num_results=5)

In [18]:
# indexsearch with new query

from minsearch import Index

index = Index(text_fields=['content'], keyword_fields=['content'])
index.fit(chunks)

text_results = index.search("How do I give the model access to tools?", num_results=5)

In [19]:
results = rrf([vector_results, text_results])
results

[{'start': 4000,
  'content': ' function. `parameters` is a JSON schema\nfor the arguments, and we mark `query` as required so the model always\nfills it in.\n\n## Sending the question with the tool\n\nNow we send the same question as before, but this time we include the\ntool in the request:\n\n```python\nresponse = openai_client.responses.create(\n    model="gpt-5.4-mini",\n    input=messages,\n    tools=[search_tool],\n)\n\nresponse.output\n```\n\nLook at the output. Instead of a message with the answer, the response\ncontains a `function_call` entry. The model decided it needs to search\nthe FAQ before answering. Rather than reply, it asked us to run the\nsearch function first.\n\nLook at the arguments too. The model didn\'t pass our question\nverbatim. It judged the raw question wasn\'t the best query to search\nwith. So it rewrote our enrollment question into search keywords like\n"enroll late join course".\n\n## Executing the function and sending the result back\n\nThe function call contains JSON arguments. We parse them, call our\n`search` function, and serialize the result.\n\n```python\nimport json\n\ncall = response.output[0]\nargs = json.loads(call.arguments)\n\nresults = search(**args)\nresult_json = json.dumps(results, indent=2)\n```\n\nNow we send this result back to the model. First, we add the model\'s\noutput to the conversation history - the model needs to see its own\nfunction call. Then we add the tool result.\n\n```python\nmessages.extend(response.output)\n\nmessages.append({\n    "type": "function_call_output",\n    "call_id": call.call_id,\n    "output": result_json,\n})\n```\n\nThe `call_id` links the tool result to the specific function call the\nmodel requested. If the model makes multiple function calls in one\nturn, each one gets its own `call_id`.\n\n## Asking the model again\n\nWe call the API a second time with the expanded history:\n\n```python\nresponse = openai_client.responses.create(\n    model="gpt-5.4-mini",\n    input=messages,\n    tools=[search_tool],\n)\n\nresponse.output_text\n```\n\nThis time the model has the original question, ',
  'filename': '01-agentic-rag/lessons/13-function-calling.md'},
 {'start': 2000,
  'content': 'wrong.\n\n## The project\n\nRAG solves these problems by giving the LLM relevant documents at\nquestion time. We don\'t hope the model memorized the answer. We\nretrieve the right information and hand it to the LLM, and the model\ngenerates a grounded response. This lets us inject knowledge the model\nnever saw during training. That\'s why RAG is still the most common way\npeople use LLMs in the industry.\n\nTo make this concrete, we build a FAQ agent for our course. A student\nasks something like "when does the course start?" and the agent answers\nfrom the FAQ data we prepared.\n\nThis module has two parts.\n\nIn Part 1 (the next 9 lessons) we will:\n\n- Understand what RAG is and how it works\n- Build a search engine over a real FAQ dataset\n- Write a prompt that combines the user\'s question with search results\n- Wire it all together into a working RAG pipeline\n- Split ingestion and query into separate processes\n\nIn Part 2, we make the pipeline agentic. The LLM decides when and\nwhat to search, instead of running the same fixed flow every time.\n\nThe final code from this module is available in the\n[code/](../code/) directory.\n\n[← Back to module](../) | [Environment →](02-environment.md)',
  'filename': '01-agentic-rag/lessons/01-intro.md'},
 {'start': 0,
  'content': '# The Agentic Loop\n\nVideo: [Watch this lesson](https://www.youtube.com/watch?v=ePlQUcTPPjw&list=PL3MmuxUbc_hLZFNgSad56pDBKK8KO0XIv)\n\nIn the previous lesson, we did function calling by hand. We sent a\nmessage and got back a function call. We ran it, sent the result back,\nand got the answer.\n\nThat works for one function call. It breaks down when the model wants\nto search several times, or when the first search misses the answer.\nWe don\'t know in advance how many calls the model will want. So we\nneed a loop that keeps calling the model and running tools until it\'s\ndone. An agent is exactly that.\n\n## Anatomy of an agent\n\nWith the LLM in the driver\'s seat, we have an agent. It\'s an AI\nassistant whose goal is to help the user.\n\nAn agent has three parts:\n\n- Instructions, the role and behavior we want. We pass this as the\n  `developer` message. The better the instructions, the better the\n  agent helps.\n- Tools, the functions the agent can call to carry out the task. For\n  us that\'s only `search`.\n- Memory, the message history. We append every prompt, every model\n  output, and every tool result. The agent reads this to know what it\n  has already tried.\n\nEverything below is the code that wires these three together inside a\nloop.\n\n## A developer prompt\n\nSo far we\'ve relied on the model to figure out when to search. We make\nthat more reliable with a `developer` message that spells out how to\nbehave. This is where we give the agent its role. The same message\nalso pushes it toward multiple searches, so we get to watch the loop\nrun more than once.\n\n```python\ninstructions = """\nYou\'re a course teaching assistant.\nYou\'re given a question from a course student and your task is to answer it.\n\nIf you want to look up information, use the search function. \nUse as many keywords from the user question as possible when making first requests.\n\nMake multiple searches.\n\nTry to expand your search by using new keywords\nbased on the results you get from the search.\n\nAt the end, ask if there are o',
  'filename': '01-agentic-rag/lessons/14-agentic-loop.md'},
 {'start': 1000,
  'content': 'swer.\n\n## Loading the documents\n\nWe\'ll use helper files from module 01 and this module.\n\nIf you don\'t have them in your notebook directory, download them:\n\n```bash\nPREFIX=https://raw.githubusercontent.com/DataTalksClub/llm-zoomcamp/main\n\nwget ${PREFIX}/01-agentic-rag/code/ingest.py\nwget ${PREFIX}/01-agentic-rag/code/rag_helper.py\nwget ${PREFIX}/04-evaluation/code/evaluation_utils.py\n```\n\nThen load the FAQ data:\n\n```python\nfrom ingest import load_faq_data\ndocuments = load_faq_data()\n```\n\nWe\'ll generate questions only for the LLM Zoomcamp FAQ. The full FAQ\ndataset contains documents from multiple courses. Generating five\nquestions for every document would take longer and cost more.\n\n```python\ndocuments_llm = []\n\nfor doc in documents:\n    if doc["course"] == "llm-zoomcamp":\n        documents_llm.append(doc)\n\nlen(documents_llm)\n```\n\nWe\'ll use these documents from now on so let\'s name them as `documents`\n\n```python\ndocuments = documents_llm\n```\n\nEach document already has an `id` field:\n\n```python\ndoc = documents[0]\nprint(doc["id"])\nprint(doc["question"])\nprint(doc["answer"])\n```\n\nThe ID becomes the label in our ground truth dataset. We generate\nquestions from a document, so we know that this document holds the\nanswer. Later, search evaluation checks whether search brings back the\ndocument with this ID.\n\nThis is why every record needs a stable ID. If you can\'t uniquely\nidentify a document, you can\'t tell whether search retrieved the right\none. When you build your own evaluation set, assign an ID to each record\nin your knowledge base first.\n\n## Generating questions with structured output\n\nWe use an LLM to generate questions for each document.\n\nThis is the first time we\'re using structured output in the course.\nWith structured output, we ask the LLM to return data in a specific\nformat instead of free-form text. For example, instead of getting a\nparagraph that contains questions, we can ask for a Python object with\na `questions` field.\n\nThis is useful when code will process ',
  'filename': '04-evaluation/lessons/02-ground-truth.md'},
 {'start': 0,
  'content': "# Other Frameworks\n\nVideo: [Watch this lesson](https://www.youtube.com/watch?v=4yiCbKX9RhI&list=PL3MmuxUbc_hLZFNgSad56pDBKK8KO0XIv)\n\nThe concepts you learned in Part 2 are the same across frameworks.\nFunction calling, the agent loop, and tool definitions all wrap the\nsame pattern. Send messages, run any function calls, and repeat until\nthe model is done.\n\nYou now understand how the loop works. So you can pick up any\nproduction framework and know what it's doing under the hood. I kept\nthis module framework agnostic on purpose, so you can explore and pick\nthe one you like.\n\nHere are some frameworks worth a look:\n\n## OpenAI Agents SDK\n\nThe official SDK from OpenAI for building agents. It uses the same\nResponses API we used throughout this module. It supports tool\ndefinition, multi-turn conversations, and handoffs between agents.\n\n```bash\nuv add openai-agents\n```\n\nGood choice if you're already using OpenAI and want something\nofficial and well-maintained.\n\n## PydanticAI\n\nA type-safe agent framework that supports multiple LLM providers.\nTools are plain Python functions with type hints, no wrappers needed.\nSwitching providers is as simple as changing the model string.\n\n```bash\nuv add pydantic-ai\n```\n\nThis is my personal favorite. The reason isn't the type safety, since\nthe other frameworks have that too. It's how it feels to use, and the\nteam behind Pydantic. Good choice if you want type safety and\nmulti-provider support.\n\n## LangChain / LangGraph\n\nA popular framework with lots of integrations. LangChain handles the\nbasics, and LangGraph adds graph-based workflows for more complex\nagent patterns.\n\nGood choice if you need lots of integrations (vector stores, document\nloaders, etc.) and a large community.\n\n## Google ADK\n\nThe Agent Development Kit from Google. If you plan to use Gemini\nmodels, this is the one I'd reach for. It exposes the same building\nblocks we've seen, like tools, instructions, and sessions. It also\nintegrates with Google Cloud.\n\nGood choice if your stack i",
  'filename': '01-agentic-rag/lessons/16-other-frameworks.md'}]

# Homework Lesson 4

In [20]:
from gitsource import GithubRepositoryDataReader

reader = GithubRepositoryDataReader(
    repo_owner="DataTalksClub",
    repo_name="llm-zoomcamp",
    commit_id="8c1834d",
    allowed_extensions={"md"},
    filename_filter=lambda path: "/lessons/" in path,
)

documents = [file.parse() for file in reader.read()]

In [22]:
len(documents)

72

In [51]:
doc = documents[:3]
doc

[{'content': '# Introduction\n\nVideo: [Watch this lesson](https://www.youtube.com/watch?v=rQYyFxf1FWw&list=PL3MmuxUbc_hLZFNgSad56pDBKK8KO0XIv)\n\nIn this module, we\'ll build a working Retrieval-Augmented\nGeneration (RAG) system from scratch, step by step.\n\nWe write everything in plain Python. We build a small search index by\nhand and call the LLM ourselves. I want you to see every piece first.\nThat way you know what a framework does for you before you reach for\none.\n\nPlaces where you can find me:\n\n- [My substack](https://alexeyondata.substack.com/)\n- [LinkedIn](https://www.linkedin.com/in/agrigorev/)\n- [X](https://x.com/Al_Grigor)\n\n## LLMs\n\nAn LLM (Large Language Model) is a neural network trained on massive\namounts of text. Given a prompt, it generates a continuation - a\nplausible next piece of text.\n\nThink of your phone. When you type "how are" in WhatsApp, it suggests\n"you" as the next word. "How are you" is the most common continuation.\nYour phone uses a simple language model for that. It predicts the next\nword based on what you typed so far.\n\nA large language model does the same thing, but at a much larger scale.\nIt has billions of parameters and is trained on most of the text on the\ninternet. When it predicts the next word, it feels like you\'re talking\nto an intelligent being. It understands what you ask and gives\nmeaningful answers.\n\nIn this course, we treat LLMs as black boxes. We won\'t look inside or\ncover the theory, and we won\'t host a model ourselves. We use an LLM\nprovider and call it over an API. For us, an LLM is a box: text goes in,\ntext comes out.\n\nBut LLMs have limitations:\n\n- Knowledge cutoff: they only know what was in their training data.\n  If you ask about something that happened after training, they won\'t\n  know - or worse, they\'ll make something up.\n- No access to your data: they can\'t see your documents, databases,\n  or internal systems unless you provide that information.\n- Hallucinations: they sometimes produce confident-sounding answers\n  that are simply wrong.\n\n## The project\n\nRAG solves these problems by giving the LLM relevant documents at\nquestion time. We don\'t hope the model memorized the answer. We\nretrieve the right information and hand it to the LLM, and the model\ngenerates a grounded response. This lets us inject knowledge the model\nnever saw during training. That\'s why RAG is still the most common way\npeople use LLMs in the industry.\n\nTo make this concrete, we build a FAQ agent for our course. A student\nasks something like "when does the course start?" and the agent answers\nfrom the FAQ data we prepared.\n\nThis module has two parts.\n\nIn Part 1 (the next 9 lessons) we will:\n\n- Understand what RAG is and how it works\n- Build a search engine over a real FAQ dataset\n- Write a prompt that combines the user\'s question with search results\n- Wire it all together into a working RAG pipeline\n- Split ingestion and query into separate processes\n\nIn Part 2, we make the pipeline agentic. The LLM decides when and\nwhat to search, instead of running the same fixed flow every time.\n\nThe final code from this module is available in the\n[code/](../code/) directory.\n\n[← Back to module](../) | [Environment →](02-environment.md)',
  'filename': '01-agentic-rag/lessons/01-intro.md'},
 {'content': '# Environment\n\nVideo: [Watch this lesson](https://www.youtube.com/watch?v=3U4gBrmkZyM&list=PL3MmuxUbc_hLZFNgSad56pDBKK8KO0XIv)\n\nFor this module, all you need is Python with Jupyter.\n\n## Prerequisites\n\nYou need the following:\n\n- Python (3.14 or later)\n- An [OpenAI account](https://openai.com/) (or an OpenAI-compatible\n  provider like Groq, Gemini, or Ollama)\n- Basic familiarity with Python and the command line\n\n## Creating the project\n\nWe\'ll start from scratch - no cloning needed. You\'ll create the\nproject yourself, step by step.\n\nFirst, install uv. It\'s a Python package manager, and I switched all my\nprojects to it because it\'s fast and convenient. Once I started using\nit, I never wanted to go back.\n\nOn Mac or Linux:\n\n```bash\ncurl -LsSf https://astral.sh/uv/install.sh | sh\n```\n\nOn Windows:\n\n```powershell\npowershell -ExecutionPolicy ByPass -c "irm https://astral.sh/uv/install.ps1 | iex"\n```\n\n(You can also use `pip install uv` if you prefer.)\n\nCreate an empty folder for the project and initialize it:\n\n```bash\nmkdir llm-zoomcamp-code\ncd llm-zoomcamp-code\nuv init\n```\n\nThis creates a `pyproject.toml` and a basic project structure.\n\nNow add the dependencies we\'ll need:\n\n```bash\nuv add requests minsearch openai jupyter python-dotenv\n```\n\nThis installs:\n\n- `requests` - to fetch the FAQ dataset from the internet\n- `minsearch` - a simple in-memory search engine for indexing and\n  searching text\n- `openai` - the OpenAI API client for calling the LLM\n- `jupyter` - the notebook environment where we\'ll write and run code\n- `python-dotenv` - to load API keys from a `.env` file\n\n## Setting up API keys\n\nWe need an API key to talk to the LLM. If you\'re using OpenAI, you\'ll\nneed to deposit some money first. The minimum is $5 (as of June 2026).\nThis lesson costs well under 10 cents to run, so that $5 goes a long\nway.\n\nI also recommend creating a separate OpenAI project for the course.\nThen you can open the usage page and see exactly how much you spent\nhere, apart from your other work.\n\nThe safest way to store the key is in a `.env` file that never gets\ncommitted to git.\n\nCreate a `.env` file in your project folder and put your API key in\nit:\n\n```bash\nOPENAI_API_KEY=sk-YOUR_KEY_HERE\n```\n\nNow add `.env` to `.gitignore` to make sure you never accidentally\ncommit your key:\n\n```bash\n.env\n```\n\nNever commit `.env` to git. Treat the API key like a password. If it\nleaks, someone else can run up charges on your account.\n\n## Starting Jupyter\n\nStart Jupyter:\n\n```bash\nuv run jupyter notebook\n```\n\nCreate a new notebook. Throughout the course, you\'ll copy code from\nthe section notes into notebook cells.\n\nCheck that the OpenAI client works:\n\n```python\nfrom dotenv import load_dotenv\nload_dotenv()\n\nfrom openai import OpenAI\nopenai_client = OpenAI()\n```\n\nIf you see an error, make sure the key in your `.env` file is\ncorrect.\n\nFor Groq or other OpenAI-compatible providers, add the key to\n`.env`:\n\n```bash\nGROQ_API_KEY=your_key_here\n```\n\nAnd configure the client:\n\n```python\nfrom openai import OpenAI\nimport os\n\nopenai_client = OpenAI(\n    api_key=os.getenv("GROQ_API_KEY"),\n    base_url="https://api.groq.com/openai/v1"\n)\n```\n\n## (Optional) Auto-loading .env with dirdotenv\n\nIf you don\'t want to call `load_dotenv()` in every notebook, use\n[dirdotenv](https://github.com/alexeygrigorev/dirdotenv).\n\nIt loads `.env` files automatically when you `cd` into a directory:\n\n```bash\nuv tool install dirdotenv\necho \'eval "$(dirdotenv hook bash)"\' >> ~/.bashrc\n```\n\nRestart your terminal, and now whenever you enter the project\ndirectory, the variables from `.env` are loaded automatically. No\n`load_dotenv()` needed.\n\n[← Introduction](01-intro.md) | [What is RAG →](03-rag.md)',
  'filename': '01-agentic-rag/lessons/02-environment.md'},
 {'content': '# RAG\n\nVideo: [Watch this lesson](https://www.youtube.com/watch?v=JktYwBIDErk&list=PL3MmuxUbc_hLZFNgSad56pDBKK8KO0XIv)\n\nWe run free Zoomcamp courses at DataTalks.Club on data engineering,\nmachine learning, MLOps, and other topics. Each course has its own\nFAQ document with common questions and answers.\n\nSome of these documents have over 300 questions. Students ask us\nthings in Slack like "Can I still join after the course started?" or\n"How do I get a certificate?" Finding those answers in the FAQ is\ntedious.\n\nWe want a bot that takes all this knowledge and answers student\nquestions in natural language.\n\nIn this module, we\'ll build that system. But first, let\'s see why we\ncan\'t send the question straight to an LLM and call it a day.\n\n## Plain LLMs lack our data\n\nFirst, let\'s define a function to talk to the LLM:\n\n```python\ndef llm(prompt):\n    response = openai_client.responses.create(\n        model="gpt-5.4-mini",\n        input=prompt\n    )\n    return response.output_text\n```\n\nThis is our black box - text goes in, text comes out.\n\nLet\'s test it:\n\n```python\nllm("Hey, what\'s up?")\n```\n\nIt replies with something. The LLM works.\n\nAsk it a course-specific\nquestion:\n\n```python\nquestion = "I just discovered the course. Can I join now?"\nanswer = llm(question)\nprint(answer)\n```\n\nThe LLM gives a generic answer. It might say "you can usually join" or\n"check the course website." It doesn\'t know about our specific Zoomcamp\ncourses, their enrollment policies, or their schedules. It tries to be\nhelpful, but has no idea about actual enrollment status or policies.\n\nThis is different from a question like "how do I cook salmon?" - the\nLLM knows the answer because cooking salmon is common knowledge. But\nour courses are not in the training data.\n\n## Adding context manually\n\nMore context can fix this. The FAQ website has questions and answers\nabout our courses.\n\nCopy some of that content into the prompt:\n\n```python\ncontext = """\nI just discovered the course. Can I still join?\nYes, but if you want to receive a certificate, you need to submit your project while we\'re still accepting submissions.\n\nCourse: I have registered for the LLM Zoomcamp. When can I expect to receive the confirmation email?\nYou don\'t need it. You\'re accepted. You can also just start learning and submitting homework (while the form is open) without registering. It is not checked against any registered list. Registration is just to gauge interest before the start date.\n\nWhat is the video/zoom link to the stream for the "Office Hours" or live/workshop sessions?\nThe zoom link is only published to instructors/presenters/TAs. Students participate via YouTube Live and submit questions to Slido.\n\nCloud alternatives with GPU\nCheck the quota and reset cycle carefully. Potential options include Google Colab, Kaggle, Databricks.\n"""\n```\n\nNotice the prompt doesn\'t end with `Answer:`. With older models like\nGPT-3 we added that to nudge the model into completing the sentence.\nModern models don\'t need the hint, so we drop it.\n\nBuild a prompt that includes both the question and the context:\n\n```python\nprompt = f"""\nYour task is to answer questions from the course participants\nbased on the provided context.\n\nUse the context to find relevant information and provide accurate\nanswers. If the answer is not found in the context,\nrespond with "I don\'t know."\n\nQuestion:\n{question}\n\nContext:\n{context}\n"""\n```\n\nInstead of sending the raw question to the LLM, we send this prompt:\n\n```python\nanswer = llm(prompt)\nprint(answer)\n```\n\nAfter that, the answer is correct: "Yes, you can still join. If you want to\nreceive a certificate, you need to submit your project while\nsubmissions are still open."\n\nThis is the answer we actually want to give to our students. What we\njust did is nothing but RAG.\n\n## Retrieval plus generation\n\nRAG stands for Retrieval-Augmented Generation. Generation is the LLM\nproducing text, and retrieval is search. We retrieve relevant documents\nfrom our knowledge base and use them to augment what the LLM generates.\nThat search step is what gives the LLM the context it needs to answer\ncorrectly.\n\nWhat we just did was naive. I knew in advance which FAQ entry held the\nanswer and pasted it in by hand. What we want instead is to perform\nsearch automatically. We take the student\'s question, find the most\nrelevant documents, and send those to the LLM.\n\nIn code, it looks like this:\n\n```python\ndef rag(question):\n    search_results = search(question)\n    user_prompt = build_prompt(question, search_results)\n    return llm(user_prompt)\n```\n\nThat\'s the entire architecture. It comes down to three components.\n\nThe pieces are search, the prompt, and the LLM:\n\n- search\n- prompt\n- LLM\n\n\n```mermaid\nflowchart TD\n    U([User])\n\n    APP[Application]\n\n    DB[(DB)]\n    DOCS[[D1 ... D5]]\n\n    PROMPT[Build Prompt<br/>Question + Context]\n\n    LLM[LLM]\n\n    ANSWER([Answer])\n\n    U -->|Question| APP\n\n    APP -->|Query| DB\n    DB -->|Retrieved Data| DOCS\n    DOCS --> APP\n\n    APP --> PROMPT\n    PROMPT --> LLM\n\n    LLM --> ANSWER\n    ANSWER --> U\n```\n\nThe LLM only sees the documents we hand it, so its answers are grounded\nin our data. If the right document is retrieved, the answer is good. If\nit\'s not, the LLM gets the wrong context and the answer is wrong. Your\nmodel is only as good as your retrieval, so search quality matters a\nlot for RAG.\n\nThe database and the LLM can be anything. In this course we use\nminsearch and then sqlitesearch for search, and OpenAI for the LLM. But\nyou can swap any component for another and see what works better.\n\nBecause each piece is independent, RAG stays flexible. To use Anthropic\ninstead of OpenAI, you swap the LLM call. To use Elasticsearch instead\nof minsearch, you swap the search call. Nothing else changes.\n\nIn the next section, we\'ll look at the dataset we\'ll use for our FAQ\nknowledge base.\n\n[← Environment](02-environment.md) | [The Course FAQ Dataset →](04-dataset.md)',
  'filename': '01-agentic-rag/lessons/03-rag.md'}]

In [25]:
from pydantic import BaseModel

class Questions(BaseModel):
    questions: list[str]

In [23]:
data_gen_instructions = """
You emulate a student who is taking our LLM course.
You are given one lesson page from the course.
Formulate 5 questions this student might ask that are answered by this page.

Rules:
- The page should contain the answer to each question.
- Make the questions complete and not too short.
- Use as few words as possible from the page; don't copy its phrasing.
- The questions should resemble how people actually ask things online:
  not too formal, not too short, not too long.
- Ask about the content of the lesson, not about its formatting or filename.
""".strip()

In [24]:
from dotenv import load_dotenv
from openai import OpenAI

load_dotenv()
openai_client = OpenAI()

In [33]:
import json
user_prompt = json.dumps(doc)

In [34]:
messages = [
    {"role": "developer", "content": data_gen_instructions},
    {"role": "user", "content": user_prompt}
]

In [35]:
response = openai_client.responses.parse(
    model="gpt-5.4-mini",
    input=messages,
    text_format=Questions
)

In [36]:
from evaluation_utils import llm_structured

In [42]:
result, usage = llm_structured(
    openai_client,
    data_gen_instructions,
    user_prompt,
    Questions
)

print(result.questions)

['What exactly is a RAG system, and how does it help an LLM answer questions better?', 'Why do LLMs make up answers or fail on recent info, and what are their main limits?', 'Why does this module build the search part and call the model directly in plain Python instead of using a framework?', 'What will be covered in the first part of the module before the agentic version starts?', 'What is the course project in this module, and what kind of FAQ problem is it trying to solve?']

In [44]:
records = []

for q in result.questions:
    records.append({
        "question": q,
        "document": doc["content"]
    })

records

[{'question': 'What exactly is a RAG system, and how does it help an LLM answer questions better?',
  'document': '# Introduction\n\nVideo: [Watch this lesson](https://www.youtube.com/watch?v=rQYyFxf1FWw&list=PL3MmuxUbc_hLZFNgSad56pDBKK8KO0XIv)\n\nIn this module, we\'ll build a working Retrieval-Augmented\nGeneration (RAG) system from scratch, step by step.\n\nWe write everything in plain Python. We build a small search index by\nhand and call the LLM ourselves. I want you to see every piece first.\nThat way you know what a framework does for you before you reach for\none.\n\nPlaces where you can find me:\n\n- [My substack](https://alexeyondata.substack.com/)\n- [LinkedIn](https://www.linkedin.com/in/agrigorev/)\n- [X](https://x.com/Al_Grigor)\n\n## LLMs\n\nAn LLM (Large Language Model) is a neural network trained on massive\namounts of text. Given a prompt, it generates a continuation - a\nplausible next piece of text.\n\nThink of your phone. When you type "how are" in WhatsApp, it suggests\n"you" as the next word. "How are you" is the most common continuation.\nYour phone uses a simple language model for that. It predicts the next\nword based on what you typed so far.\n\nA large language model does the same thing, but at a much larger scale.\nIt has billions of parameters and is trained on most of the text on the\ninternet. When it predicts the next word, it feels like you\'re talking\nto an intelligent being. It understands what you ask and gives\nmeaningful answers.\n\nIn this course, we treat LLMs as black boxes. We won\'t look inside or\ncover the theory, and we won\'t host a model ourselves. We use an LLM\nprovider and call it over an API. For us, an LLM is a box: text goes in,\ntext comes out.\n\nBut LLMs have limitations:\n\n- Knowledge cutoff: they only know what was in their training data.\n  If you ask about something that happened after training, they won\'t\n  know - or worse, they\'ll make something up.\n- No access to your data: they can\'t see your documents, databases,\n  or internal systems unless you provide that information.\n- Hallucinations: they sometimes produce confident-sounding answers\n  that are simply wrong.\n\n## The project\n\nRAG solves these problems by giving the LLM relevant documents at\nquestion time. We don\'t hope the model memorized the answer. We\nretrieve the right information and hand it to the LLM, and the model\ngenerates a grounded response. This lets us inject knowledge the model\nnever saw during training. That\'s why RAG is still the most common way\npeople use LLMs in the industry.\n\nTo make this concrete, we build a FAQ agent for our course. A student\nasks something like "when does the course start?" and the agent answers\nfrom the FAQ data we prepared.\n\nThis module has two parts.\n\nIn Part 1 (the next 9 lessons) we will:\n\n- Understand what RAG is and how it works\n- Build a search engine over a real FAQ dataset\n- Write a prompt that combines the user\'s question with search results\n- Wire it all together into a working RAG pipeline\n- Split ingestion and query into separate processes\n\nIn Part 2, we make the pipeline agentic. The LLM decides when and\nwhat to search, instead of running the same fixed flow every time.\n\nThe final code from this module is available in the\n[code/](../code/) directory.\n\n[← Back to module](../) | [Environment →](02-environment.md)'},
 {'question': 'Why do LLMs make up answers or fail on recent info, and what are their main limits?',
  'document': '# Introduction\n\nVideo: [Watch this lesson](https://www.youtube.com/watch?v=rQYyFxf1FWw&list=PL3MmuxUbc_hLZFNgSad56pDBKK8KO0XIv)\n\nIn this module, we\'ll build a working Retrieval-Augmented\nGeneration (RAG) system from scratch, step by step.\n\nWe write everything in plain Python. We build a small search index by\nhand and call the LLM ourselves. I want you to see every piece first.\nThat way you know what a framework does for you before you reach for\none.\n\nPlaces where you can find me:\n\n- [My substack](https://alexeyondata.substack.com/)\n- [LinkedIn](https://www.linkedin.com/in/agrigorev/)\n- [X](https://x.com/Al_Grigor)\n\n## LLMs\n\nAn LLM (Large Language Model) is a neural network trained on massive\namounts of text. Given a prompt, it generates a continuation - a\nplausible next piece of text.\n\nThink of your phone. When you type "how are" in WhatsApp, it suggests\n"you" as the next word. "How are you" is the most common continuation.\nYour phone uses a simple language model for that. It predicts the next\nword based on what you typed so far.\n\nA large language model does the same thing, but at a much larger scale.\nIt has billions of parameters and is trained on most of the text on the\ninternet. When it predicts the next word, it feels like you\'re talking\nto an intelligent being. It understands what you ask and gives\nmeaningful answers.\n\nIn this course, we treat LLMs as black boxes. We won\'t look inside or\ncover the theory, and we won\'t host a model ourselves. We use an LLM\nprovider and call it over an API. For us, an LLM is a box: text goes in,\ntext comes out.\n\nBut LLMs have limitations:\n\n- Knowledge cutoff: they only know what was in their training data.\n  If you ask about something that happened after training, they won\'t\n  know - or worse, they\'ll make something up.\n- No access to your data: they can\'t see your documents, databases,\n  or internal systems unless you provide that information.\n- Hallucinations: they sometimes produce confident-sounding answers\n  that are simply wrong.\n\n## The project\n\nRAG solves these problems by giving the LLM relevant documents at\nquestion time. We don\'t hope the model memorized the answer. We\nretrieve the right information and hand it to the LLM, and the model\ngenerates a grounded response. This lets us inject knowledge the model\nnever saw during training. That\'s why RAG is still the most common way\npeople use LLMs in the industry.\n\nTo make this concrete, we build a FAQ agent for our course. A student\nasks something like "when does the course start?" and the agent answers\nfrom the FAQ data we prepared.\n\nThis module has two parts.\n\nIn Part 1 (the next 9 lessons) we will:\n\n- Understand what RAG is and how it works\n- Build a search engine over a real FAQ dataset\n- Write a prompt that combines the user\'s question with search results\n- Wire it all together into a working RAG pipeline\n- Split ingestion and query into separate processes\n\nIn Part 2, we make the pipeline agentic. The LLM decides when and\nwhat to search, instead of running the same fixed flow every time.\n\nThe final code from this module is available in the\n[code/](../code/) directory.\n\n[← Back to module](../) | [Environment →](02-environment.md)'},
 {'question': 'Why does this module build the search part and call the model directly in plain Python instead of using a framework?',
  'document': '# Introduction\n\nVideo: [Watch this lesson](https://www.youtube.com/watch?v=rQYyFxf1FWw&list=PL3MmuxUbc_hLZFNgSad56pDBKK8KO0XIv)\n\nIn this module, we\'ll build a working Retrieval-Augmented\nGeneration (RAG) system from scratch, step by step.\n\nWe write everything in plain Python. We build a small search index by\nhand and call the LLM ourselves. I want you to see every piece first.\nThat way you know what a framework does for you before you reach for\none.\n\nPlaces where you can find me:\n\n- [My substack](https://alexeyondata.substack.com/)\n- [LinkedIn](https://www.linkedin.com/in/agrigorev/)\n- [X](https://x.com/Al_Grigor)\n\n## LLMs\n\nAn LLM (Large Language Model) is a neural network trained on massive\namounts of text. Given a prompt, it generates a continuation - a\nplausible next piece of text.\n\nThink of your phone. When you type "how are" in WhatsApp, it suggests\n"you" as the next word. "How are you" is the most common continuation.\nYour phone uses a simple language model for that. It predicts the next\nword based on what you typed so far.\n\nA large language model does the same thing, but at a much larger scale.\nIt has billions of parameters and is trained on most of the text on the\ninternet. When it predicts the next word, it feels like you\'re talking\nto an intelligent being. It understands what you ask and gives\nmeaningful answers.\n\nIn this course, we treat LLMs as black boxes. We won\'t look inside or\ncover the theory, and we won\'t host a model ourselves. We use an LLM\nprovider and call it over an API. For us, an LLM is a box: text goes in,\ntext comes out.\n\nBut LLMs have limitations:\n\n- Knowledge cutoff: they only know what was in their training data.\n  If you ask about something that happened after training, they won\'t\n  know - or worse, they\'ll make something up.\n- No access to your data: they can\'t see your documents, databases,\n  or internal systems unless you provide that information.\n- Hallucinations: they sometimes produce confident-sounding answers\n  that are simply wrong.\n\n## The project\n\nRAG solves these problems by giving the LLM relevant documents at\nquestion time. We don\'t hope the model memorized the answer. We\nretrieve the right information and hand it to the LLM, and the model\ngenerates a grounded response. This lets us inject knowledge the model\nnever saw during training. That\'s why RAG is still the most common way\npeople use LLMs in the industry.\n\nTo make this concrete, we build a FAQ agent for our course. A student\nasks something like "when does the course start?" and the agent answers\nfrom the FAQ data we prepared.\n\nThis module has two parts.\n\nIn Part 1 (the next 9 lessons) we will:\n\n- Understand what RAG is and how it works\n- Build a search engine over a real FAQ dataset\n- Write a prompt that combines the user\'s question with search results\n- Wire it all together into a working RAG pipeline\n- Split ingestion and query into separate processes\n\nIn Part 2, we make the pipeline agentic. The LLM decides when and\nwhat to search, instead of running the same fixed flow every time.\n\nThe final code from this module is available in the\n[code/](../code/) directory.\n\n[← Back to module](../) | [Environment →](02-environment.md)'},
 {'question': 'What will be covered in the first part of the module before the agentic version starts?',
  'document': '# Introduction\n\nVideo: [Watch this lesson](https://www.youtube.com/watch?v=rQYyFxf1FWw&list=PL3MmuxUbc_hLZFNgSad56pDBKK8KO0XIv)\n\nIn this module, we\'ll build a working Retrieval-Augmented\nGeneration (RAG) system from scratch, step by step.\n\nWe write everything in plain Python. We build a small search index by\nhand and call the LLM ourselves. I want you to see every piece first.\nThat way you know what a framework does for you before you reach for\none.\n\nPlaces where you can find me:\n\n- [My substack](https://alexeyondata.substack.com/)\n- [LinkedIn](https://www.linkedin.com/in/agrigorev/)\n- [X](https://x.com/Al_Grigor)\n\n## LLMs\n\nAn LLM (Large Language Model) is a neural network trained on massive\namounts of text. Given a prompt, it generates a continuation - a\nplausible next piece of text.\n\nThink of your phone. When you type "how are" in WhatsApp, it suggests\n"you" as the next word. "How are you" is the most common continuation.\nYour phone uses a simple language model for that. It predicts the next\nword based on what you typed so far.\n\nA large language model does the same thing, but at a much larger scale.\nIt has billions of parameters and is trained on most of the text on the\ninternet. When it predicts the next word, it feels like you\'re talking\nto an intelligent being. It understands what you ask and gives\nmeaningful answers.\n\nIn this course, we treat LLMs as black boxes. We won\'t look inside or\ncover the theory, and we won\'t host a model ourselves. We use an LLM\nprovider and call it over an API. For us, an LLM is a box: text goes in,\ntext comes out.\n\nBut LLMs have limitations:\n\n- Knowledge cutoff: they only know what was in their training data.\n  If you ask about something that happened after training, they won\'t\n  know - or worse, they\'ll make something up.\n- No access to your data: they can\'t see your documents, databases,\n  or internal systems unless you provide that information.\n- Hallucinations: they sometimes produce confident-sounding answers\n  that are simply wrong.\n\n## The project\n\nRAG solves these problems by giving the LLM relevant documents at\nquestion time. We don\'t hope the model memorized the answer. We\nretrieve the right information and hand it to the LLM, and the model\ngenerates a grounded response. This lets us inject knowledge the model\nnever saw during training. That\'s why RAG is still the most common way\npeople use LLMs in the industry.\n\nTo make this concrete, we build a FAQ agent for our course. A student\nasks something like "when does the course start?" and the agent answers\nfrom the FAQ data we prepared.\n\nThis module has two parts.\n\nIn Part 1 (the next 9 lessons) we will:\n\n- Understand what RAG is and how it works\n- Build a search engine over a real FAQ dataset\n- Write a prompt that combines the user\'s question with search results\n- Wire it all together into a working RAG pipeline\n- Split ingestion and query into separate processes\n\nIn Part 2, we make the pipeline agentic. The LLM decides when and\nwhat to search, instead of running the same fixed flow every time.\n\nThe final code from this module is available in the\n[code/](../code/) directory.\n\n[← Back to module](../) | [Environment →](02-environment.md)'},
 {'question': 'What is the course project in this module, and what kind of FAQ problem is it trying to solve?',
  'document': '# Introduction\n\nVideo: [Watch this lesson](https://www.youtube.com/watch?v=rQYyFxf1FWw&list=PL3MmuxUbc_hLZFNgSad56pDBKK8KO0XIv)\n\nIn this module, we\'ll build a working Retrieval-Augmented\nGeneration (RAG) system from scratch, step by step.\n\nWe write everything in plain Python. We build a small search index by\nhand and call the LLM ourselves. I want you to see every piece first.\nThat way you know what a framework does for you before you reach for\none.\n\nPlaces where you can find me:\n\n- [My substack](https://alexeyondata.substack.com/)\n- [LinkedIn](https://www.linkedin.com/in/agrigorev/)\n- [X](https://x.com/Al_Grigor)\n\n## LLMs\n\nAn LLM (Large Language Model) is a neural network trained on massive\namounts of text. Given a prompt, it generates a continuation - a\nplausible next piece of text.\n\nThink of your phone. When you type "how are" in WhatsApp, it suggests\n"you" as the next word. "How are you" is the most common continuation.\nYour phone uses a simple language model for that. It predicts the next\nword based on what you typed so far.\n\nA large language model does the same thing, but at a much larger scale.\nIt has billions of parameters and is trained on most of the text on the\ninternet. When it predicts the next word, it feels like you\'re talking\nto an intelligent being. It understands what you ask and gives\nmeaningful answers.\n\nIn this course, we treat LLMs as black boxes. We won\'t look inside or\ncover the theory, and we won\'t host a model ourselves. We use an LLM\nprovider and call it over an API. For us, an LLM is a box: text goes in,\ntext comes out.\n\nBut LLMs have limitations:\n\n- Knowledge cutoff: they only know what was in their training data.\n  If you ask about something that happened after training, they won\'t\n  know - or worse, they\'ll make something up.\n- No access to your data: they can\'t see your documents, databases,\n  or internal systems unless you provide that information.\n- Hallucinations: they sometimes produce confident-sounding answers\n  that are simply wrong.\n\n## The project\n\nRAG solves these problems by giving the LLM relevant documents at\nquestion time. We don\'t hope the model memorized the answer. We\nretrieve the right information and hand it to the LLM, and the model\ngenerates a grounded response. This lets us inject knowledge the model\nnever saw during training. That\'s why RAG is still the most common way\npeople use LLMs in the industry.\n\nTo make this concrete, we build a FAQ agent for our course. A student\nasks something like "when does the course start?" and the agent answers\nfrom the FAQ data we prepared.\n\nThis module has two parts.\n\nIn Part 1 (the next 9 lessons) we will:\n\n- Understand what RAG is and how it works\n- Build a search engine over a real FAQ dataset\n- Write a prompt that combines the user\'s question with search results\n- Wire it all together into a working RAG pipeline\n- Split ingestion and query into separate processes\n\nIn Part 2, we make the pipeline agentic. The LLM decides when and\nwhat to search, instead of running the same fixed flow every time.\n\nThe final code from this module is available in the\n[code/](../code/) directory.\n\n[← Back to module](../) | [Environment →](02-environment.md)'}]

In [45]:
from evaluation_utils import llm_structured_retry

In [47]:
def generate_ground_truth(doc):
    user_prompt = json.dumps(doc)

    out, usage = llm_structured_retry(
        openai_client,
        data_gen_instructions,
        user_prompt,
        Questions
    )

    results = []

    for q in out.questions:
        results.append({
            "question": q,
            "document": doc["content"]
        })

    return results, usage

**Q1. Generating questions**

In [48]:
from tqdm.auto import tqdm

ground_truth = []
usages = []

for doc in tqdm(documents[:3]):
    records, usage = generate_ground_truth(doc)
    ground_truth.extend(records)
    usages.append(usage)

  0%|          | 0/3 [00:00<?, ?it/s]

In [50]:
import pandas as pd
pd.DataFrame(records)

,question,document
0,Why doesn't a plain LLM give a good answer whe...,# RAG\n\nVideo: [Watch this lesson](https://ww...
1,What changes when you put FAQ text into the pr...,# RAG\n\nVideo: [Watch this lesson](https://ww...
2,"What does RAG mean, and what are the two main ...",# RAG\n\nVideo: [Watch this lesson](https://ww...
3,How does the bot decide which FAQ entries to s...,# RAG\n\nVideo: [Watch this lesson](https://ww...
4,Why is the retrieval step so important in a RA...,# RAG\n\nVideo: [Watch this lesson](https://ww...

In [53]:
avg_input_tokens = sum(u.input_tokens for u in usages) / len(usages)
avg_input_tokens

1353.0

In [56]:
from gitsource import chunk_documents

chunks = chunk_documents(documents, size=2000, step=1000)

In [57]:
chunk_contents = [chunk["content"] for chunk in chunks]
vectors = embed.encode_batch(chunk_contents)

len(vectors)

295

In [62]:
text_index = Index(text_fields=["content"], keyword_fields=["filename"])
text_index.fit(chunks)

vector_index = VectorSearch(keyword_fields=["filename"])
vector_index.fit(X, chunks)

def text_search(query: str, num_results: int = 5):
    return text_index.search(query, num_results=num_results)

def vector_search(query: str, num_results: int = 5):
    q_vec = embed.encode(query)
    return vector_index.search(q_vec, num_results=num_results)

In [63]:
def rrf(result_lists, k=60, num_results=5):
    scores = {}
    docs = {}

    for results in result_lists:
        for rank, doc in enumerate(results):
            key = (doc["filename"], doc["start"])
            scores[key] = scores.get(key, 0) + 1 / (k + rank)
            docs[key] = doc

    ranked = sorted(scores, key=scores.get, reverse=True)
    return [docs[key] for key in ranked[:num_results]]

In [64]:
def hybrid_search(query, k=60):
    text_results = text_search(query, num_results=10)
    vector_results = vector_search(query, num_results=10)
    return rrf([text_results, vector_results], k=k)

**Q2. First result with text search**

In [65]:
q = ground_truth[0]["question"]

In [70]:
q

'What is a retrieval-augmented generation system, in simple terms, and why would you use it instead of relying on the model alone?'

In [68]:
text_results = text_search(q, num_results=5)
text_results[0]

{'start': 3000,
 'content': 'we drop it.\n\nBuild a prompt that includes both the question and the context:\n\n```python\nprompt = f"""\nYour task is to answer questions from the course participants\nbased on the provided context.\n\nUse the context to find relevant information and provide accurate\nanswers. If the answer is not found in the context,\nrespond with "I don\'t know."\n\nQuestion:\n{question}\n\nContext:\n{context}\n"""\n```\n\nInstead of sending the raw question to the LLM, we send this prompt:\n\n```python\nanswer = llm(prompt)\nprint(answer)\n```\n\nAfter that, the answer is correct: "Yes, you can still join. If you want to\nreceive a certificate, you need to submit your project while\nsubmissions are still open."\n\nThis is the answer we actually want to give to our students. What we\njust did is nothing but RAG.\n\n## Retrieval plus generation\n\nRAG stands for Retrieval-Augmented Generation. Generation is the LLM\nproducing text, and retrieval is search. We retrieve relevant documents\nfrom our knowledge base and use them to augment what the LLM generates.\nThat search step is what gives the LLM the context it needs to answer\ncorrectly.\n\nWhat we just did was naive. I knew in advance which FAQ entry held the\nanswer and pasted it in by hand. What we want instead is to perform\nsearch automatically. We take the student\'s question, find the most\nrelevant documents, and send those to the LLM.\n\nIn code, it looks like this:\n\n```python\ndef rag(question):\n    search_results = search(question)\n    user_prompt = build_prompt(question, search_results)\n    return llm(user_prompt)\n```\n\nThat\'s the entire architecture. It comes down to three components.\n\nThe pieces are search, the prompt, and the LLM:\n\n- search\n- prompt\n- LLM\n\n\n```mermaid\nflowchart TD\n    U([User])\n\n    APP[Application]\n\n    DB[(DB)]\n    DOCS[[D1 ... D5]]\n\n    PROMPT[Build Prompt<br/>Question + Context]\n\n    LLM[LLM]\n\n    ANSWER([Answer])\n\n    U -->|Question| APP\n\n    APP -->|Query| DB\n    DB -->|Retrieved Data| DOCS\n    DOCS --> APP\n\n    APP --> PROMPT\n    PROMPT -',
 'filename': '01-agentic-rag/lessons/03-rag.md'}

**Q3. First result with vector search**

In [69]:
vector_results = vector_search(q, num_results=5)
vector_results[0]

{'start': 0,
 'content': '# Introduction\n\nVideo: [Watch this lesson](https://www.youtube.com/watch?v=rQYyFxf1FWw&list=PL3MmuxUbc_hLZFNgSad56pDBKK8KO0XIv)\n\nIn this module, we\'ll build a working Retrieval-Augmented\nGeneration (RAG) system from scratch, step by step.\n\nWe write everything in plain Python. We build a small search index by\nhand and call the LLM ourselves. I want you to see every piece first.\nThat way you know what a framework does for you before you reach for\none.\n\nPlaces where you can find me:\n\n- [My substack](https://alexeyondata.substack.com/)\n- [LinkedIn](https://www.linkedin.com/in/agrigorev/)\n- [X](https://x.com/Al_Grigor)\n\n## LLMs\n\nAn LLM (Large Language Model) is a neural network trained on massive\namounts of text. Given a prompt, it generates a continuation - a\nplausible next piece of text.\n\nThink of your phone. When you type "how are" in WhatsApp, it suggests\n"you" as the next word. "How are you" is the most common continuation.\nYour phone uses a simple language model for that. It predicts the next\nword based on what you typed so far.\n\nA large language model does the same thing, but at a much larger scale.\nIt has billions of parameters and is trained on most of the text on the\ninternet. When it predicts the next word, it feels like you\'re talking\nto an intelligent being. It understands what you ask and gives\nmeaningful answers.\n\nIn this course, we treat LLMs as black boxes. We won\'t look inside or\ncover the theory, and we won\'t host a model ourselves. We use an LLM\nprovider and call it over an API. For us, an LLM is a box: text goes in,\ntext comes out.\n\nBut LLMs have limitations:\n\n- Knowledge cutoff: they only know what was in their training data.\n  If you ask about something that happened after training, they won\'t\n  know - or worse, they\'ll make something up.\n- No access to your data: they can\'t see your documents, databases,\n  or internal systems unless you provide that information.\n- Hallucinations: they sometimes produce confident-sounding answers\n  that are simply ',
 'filename': '01-agentic-rag/lessons/01-intro.md'}

In [83]:
def compute_relevance(q, search_function):
    doc_id = q["document"]
    results = search_function(query=q["question"])

    relevance = []
    for d in results:
        relevance.append(int(d["filename"] == doc_id))

    return relevance

In [84]:
def compute_relevance_total(ground_truth, search_function):
    relevance_total = []

    for q in tqdm(ground_truth):
        relevance = compute_relevance(q, search_function)
        relevance_total.append(relevance)

    return relevance_total

In [85]:
def hit_rate(relevance):
    cnt = 0

    for line in relevance:
        if 1 in line:
            cnt = cnt + 1

    return cnt / len(relevance)

In [86]:
def mrr(relevance):
    total_score = 0.0

    for line in relevance:
        for rank in range(len(line)):
            if line[rank] == 1:
                score = 1 / (rank + 1)
                total_score = total_score + score
                break

    return total_score / len(relevance)

In [90]:
def evaluate(ground_truth, search_function):
    relevance_total = compute_relevance_total(ground_truth, search_function)

    return {
        "hit_rate": hit_rate(relevance_total),
        "mrr": mrr(relevance_total),
    }

In [97]:
doc_content_to_filename = {doc["content"]: doc["filename"] for doc in documents}

def compute_relevance(q, search_function):
    doc_filename = doc_content_to_filename[q["document"]]
    results = search_function(query=q["question"])

    return [int(d["filename"] == doc_filename) for d in results]

**Q4. Evaluating text search**

In [98]:

evaluate(ground_truth, text_search)

  0%|          | 0/15 [00:00<?, ?it/s]

{'hit_rate': 0.7333333333333333, 'mrr': 0.6222222222222221}

****Q5. Evaluating vector search****

In [99]:
evaluate(ground_truth, vector_search)

  0%|          | 0/15 [00:00<?, ?it/s]

{'hit_rate': 0.6666666666666666, 'mrr': 0.4488888888888889}

****Q6. Tuning hybrid search****

In [100]:
import pandas as pd

ks = [1, 50, 100, 200]
mrrs = {}

for k in ks:
    print(f"Running hybrid_search with k={k}...")
    mrrs[k] = evaluate(ground_truth, lambda query, k=k: hybrid_search(query, k=k))["mrr"]

pd.DataFrame.from_dict(mrrs, orient="index", columns=["mrr"])

Running hybrid_search with k=1...

  0%|          | 0/15 [00:00<?, ?it/s]

Running hybrid_search with k=50...

  0%|          | 0/15 [00:00<?, ?it/s]

Running hybrid_search with k=100...

  0%|          | 0/15 [00:00<?, ?it/s]

Running hybrid_search with k=200...

  0%|          | 0/15 [00:00<?, ?it/s]

          mrr
1    0.627778
50   0.583333
100  0.583333
200  0.583333